### ISSUE TITLE
Error with Elytra

### ISSUE THREAD

**Issue by tienthanh23423** [MrStrace/TWINGS#1]
[ERROR] .... Error occurred while enabling TWINGS v2.0.8 (Is it up to date?)

java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.LEGACY_elytra

at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_272]

at org.bukkit.Material.valueOf(Material.java:88) ~[patched_1.16.1.jar:git-Paper-138]

at org.bukkit.craftbukkit.v1_16_R1.legacy.CraftLegacy.valueOf(CraftLegacy.java:227) ~[patched_1.16.1.jar:git-Paper-138]

at dev.strace.twings.utils.objects.Wing.<init>(Wing.java:77) ~[?:?]

at dev.strace.twings.utils.WingReader.registerWings(WingReader.java:27) ~[?:?]

at dev.strace.twings.Main.load(Main.java:78) ~[?:?]

at dev.strace.twings.Main.onEnable(Main.java:57) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-138]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-138]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-138]

at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-138]

at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-138]

at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-138]

at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-138]

at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-138]

at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-138]

at net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2924/0x0000000071a71240.run(Unknown Source) ~[?:?]

at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]

**Comment by MrStrace** [comment]
What Material Name did you use in the .yml, was it "ELYTRA" or "LEGACY_ELYTRA"?

**Comment by tienthanh23423** [comment]
> What Material Name did you use in the .yml, was it "ELYTRA" or "LEGACY_ELYTRA"?

Sorry for late reply. I did manage to fix it as I was a chestcommand user, and it requires caps word. I look into the error and looks like LEGACY is caps, so I changed to ELYTRA and it works flawlessly. Lock thread
